version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb://197.136.183.22:27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME="${MONGO_EXPRESS_USERNAME:-username}"
      - ME_CONFIG_BASICAUTH_PASSWORD="${MONGO_EXPRESS_PASSWORD:-password}"
    depends_on:
      - mongo
